# Generated by Django 3.0.7 on 2020-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200630_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Feito'), (2, 'Cancelado')], default=0),
        ),
    ]
